# Generated by Django 3.2.4 on 2022-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='email@yandex.ru', help_text='Введите почту', max_length=254),
        ),
    ]
