# Generated by Django 3.2.4 on 2022-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Введите почту', max_length=254),
        ),
    ]
