# Generated by Django 3.2 on 2022-11-09 16:58

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандартное название', help_text='до 150 символов', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='уникальное значение до 200 символов(только латинца, цифры, _ и -)', max_length=200, unique=True, validators=[catalog.validators.validate_regex], verbose_name='Идентификатор')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('weight', models.IntegerField(default=100, help_text='Рейтинг товара, в интервале (0,32767)', validators=[catalog.validators.validate_weight_range], verbose_name='Рейтинг товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандартное название', help_text='до 150 символов', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('text', tinymce.models.HTMLField(help_text='Введите описание товара, состоящее не менее чем из двух слов, содержающее "превосходно" или "роскошно"', validators=[catalog.validators.validate_item_need('превосходно', 'роскошно')], verbose_name='Описание товара')),
                ('category', models.ForeignKey(help_text='Выберите одну категорию товара', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандартное название', help_text='до 150 символов', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='уникальное значение до 200 символов(только латинца, цифры, _ и -)', max_length=200, unique=True, validators=[catalog.validators.validate_regex], verbose_name='Идентификатор')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('upload', models.ImageField(help_text='Главное изображение товара', upload_to='uploads/preview/%Y/%m', verbose_name='Превью')),
                ('item', models.OneToOneField(help_text='Выбранный товар', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Превью',
                'verbose_name_plural': 'Превьюшечки',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(help_text='Загрузите изображение товара', upload_to='uploads/gallery/%Y/%m', verbose_name='Изображение товара')),
                ('item', models.ForeignKey(help_text='Выбранный товар', on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлереи',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите не менее одного тега товара', related_name='items', to='catalog.Tag', verbose_name='Теги'),
        ),
    ]
